# 网站信息
title: 风雨雾凇
subtitle:
description:
keywords: 博客, 风雨雾凇
author: 风雨雾凇
language:
  - zh-CN
  - en
  - zh-HK
  - zh-TW
timezone: Asia/Shanghai
shortcut_icon: "https://pic.fengyuwusong.cn/avatar.png"
favicon: "https://pic.fengyuwusong.cn/avatar.png"
avatar: "https://pic.fengyuwusong.cn/avatar.png"

# 网站链接配
url: https://fengyuwsuong.cn
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# 导航栏
nav_menu:
  - name: 主页
    icon: fas fa-home
    url: https://fengyuwusong.cn/
  # - name: 项目
  #   icon: fas fa-flask
  #   url: https://fengyuwusong.cn/projects/
  - name: 博客
    icon: fas fa-rss
    url: /
  - name: 归档
    icon: fas fa-archive
    url: archives/
  - name: 关于
    icon: fas fa-user
    url: https://fengyuwusong.cn/fengyuwusong

# Directory
source_dir: source
public_dir: public
#tag_dir: tags
#archive_dir: archives
#category_dir: categories
#code_dir: downloads/code
#i18n_dir: :lang
#skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: material-x


# 评论系统设置
leancloud:
  app_id: 4ostjPGgQz6dtae97OShmQBj-gzGzoHsz
  app_key: vEFK2xQiAC3hKlgcL3wY0HGI

# 自动生成sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:fengyuwusong/fengyuwusong.github.io.git
  branch: master
  message: "feature(*): 更改遗漏未替换为https的图床链接"
  name: fengyuwusong
  email: 602766695@qq.com
